name: application workflow
on: 
  workflow_dispatch: 
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      
      - name: set up jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'tumurin'
          cache: maven
      - name: Install maven
        run: |
          sudo apt update
          sudo apt install maven -y
      - name: build the artifact
        run: mvn clean package
        
        
        
       
          
          
           
      
